### ISSUE TITLE
Support for Card Matching Event

### ISSUE THREAD

**Issue by rocity** [patpatpatpatpat/roph-rewards#10]
Announcement Link:
https://www.ragnarokonline.com.ph/news/card-matching

Event Duration:
Nov 15, 2017 to Dec 13, 2017

Mechanics:
> Match 8x8 cards, player will be able to open 6 pairs of cards per day and are able to gain 4 more chances to open the cards from sharing the event on to Facebook (Total of 10 times/day)

**Comment by rocity** [comment]
Algorithm:
[Building a Memory Game](https://ritterit-programming.wikispaces.com/06.+Memory+Game)

**Comment by patpatpatpatpat** [comment]
Implemented here: https://github.com/patpatpatpatpat/roph-rewards/releases/tag/1.3.0
