### ISSUE TITLE
roPH March Bingo

### ISSUE THREAD

**Issue by twistedalpha** [patpatpatpatpat/roph-rewards#19]
March Bingo Lucky Get Free Item

Event page:
[March Bingo](https://ragnarokonline.com.ph/news/bingo-mar2018)

**Comment by albeedelacruz** [comment]
Yes! Support for the new event please :D

**Comment by patpatpatpatpat** [comment]
https://github.com/patpatpatpatpat/roph-rewards/releases/tag/v1.6.0

IMPORTANT NOTE: EXE websites (ROPH & MYSG) fixed the "Share to FB" bug, which means it can't be bypassed anymore using the script. You now need to use a valid FB account to gain more chances in their web activities.

**Comment by albeedelacruz** [comment]
Thanks!
